SELECT * FROM (
    SELECT 
        1                        AS num_ligne,
        'CNTRCT_ID'              AS IDENTIFIANT_CONTRAT,
        'INSTRMNT_ID'            AS IDENTIFIANT_INSTRUMENT,
        'NEW'                    AS NOUVEAU,
        'I06'                    AS TYPE_INSTRUMENT,
        'I38'                    AS SOUS_TYPE_INSTRUMENT,
        'I27'                    AS CATEGORIE_INSTRUMENT,
        'I08'                    AS DEVISE,
        'I09'                    AS DATE_CREATION,
        'I11'                    AS DATE_ECHEANCE_FINALE_LEGALE,
        'I18'                    AS NOMBRE_TERMES,
        'I19'                    AS MONTANT_TERME,
        'I20'                    AS DATE_PREMIER_TERME,
        'I21'                    AS DATE_REMBOURSEMENT_ANTICIPE,
        'I39'                    AS MONTANT_ENGAGEMENT,
        'I40'                    AS MONTANT_TOTAL_REMBOURSER,
        'I24'                    AS FREQUENCE_PAIEMENT,
        'I26'                    AS FINALITE,
        'I35'                    AS DATE_FIN_INSTRUMENT,
        'I41'                    AS SURETE_HYPOTHECAIRE,
        'I42'                    AS REFINANCEMENT,
        'I43'                    AS LANGUE_CONTRAT,
        'I44'                    AS TOUS_DEBITEURS_NON_RESIDENTS_CREATION,
        'I45'                    AS DATE_SUBSTITUTION,
        'F11'                    AS ETAT_DEFAUT_INSTRUMENT,
        'F12'                    AS DATE_ETAT_DEFAUT_INSTRUMENT,
        'F24'                    AS DATE_MONTANT_ARRIERES,
        'F15'                    AS MONTANT_ARRIERES,
        'F18'                    AS ETAT_EXIGIBILITE,
        'F19'                    AS DATE_ETAT_EXIGIBILITE,
        'F25'                    AS ETAT_REGULARISATION,
        'F26'                    AS DATE_ETAT_REGULARISATION,
        'F27'                    AS UTILISATION_MONTANT_ENGAGEMENT,
        'REF_XLS'                AS LIGNE_EXCEL,
        'REF_AUDIT'              AS LIGNE_AUDIT,
        0                        AS SORT_ORDER
    FROM DUAL
    UNION ALL
    SELECT 
        LIGNE_EXCEL + 1          AS num_ligne,
        IDENTIFIANT_CONTRAT,
        IDENTIFIANT_INSTRUMENT,
        NOUVEAU,
        TYPE_INSTRUMENT,
        SOUS_TYPE_INSTRUMENT,
        CATEGORIE_INSTRUMENT,
        DEVISE,
        DATE_CREATION,
        DATE_ECHEANCE_FINALE_LEGALE,
        NOMBRE_TERMES,
        MONTANT_TERME,
        DATE_PREMIER_TERME,
        DATE_REMBOURSEMENT_ANTICIPE,
        MONTANT_ENGAGEMENT,
        MONTANT_TOTAL_REMBOURSER,
        FREQUENCE_PAIEMENT,
        FINALITE,
        TO_CHAR(DATE_FIN_INSTRUMENT, 'DD/MM/YYYY'),
        SURETE_HYPOTHECAIRE,
        REFINANCEMENT,
        LANGUE_CONTRAT,
        TOUS_DEBITEURS_NON_RESIDENTS_CREATION,
        DATE_SUBSTITUTION,
        ETAT_DEFAUT_INSTRUMENT,
        TO_CHAR(DATE_ETAT_DEFAUT_INSTRUMENT, 'DD/MM/YYYY'),
        TO_CHAR(DATE_MONTANT_ARRIERES, 'DD/MM/YYYY'),
        TO_CHAR(MONTANT_ARRIERES),
        ETAT_EXIGIBILITE,
        TO_CHAR(DATE_ETAT_EXIGIBILITE, 'DD/MM/YYYY'),
        ETAT_REGULARISATION,
        TO_CHAR(DATE_ETAT_REGULARISATION, 'DD/MM/YYYY'),
        UTILISATION_MONTANT_ENGAGEMENT,
        TO_CHAR(LIGNE_EXCEL),
        LIGNE_AUDIT,
        1                        AS SORT_ORDER
    FROM BECRIS_INSTRUMENT
    ORDER BY SORT_ORDER, LIGNE_EXCEL
) ORDER BY num_ligne;